# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-20 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyYieldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasury_id', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='Date for Treasury Yield Data')),
                ('is_inverted', models.BooleanField(default=False)),
                ('one_month_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('two_month_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('three_month_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('six_month_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('one_year_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('two_year_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('three_year_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('five_year_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('seven_year_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ten_year_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('twenty_year_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('thirty_year_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
