# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yc_app', '0002_auto_20190820_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date for Treasury Yield Data')),
                ('rate_type', models.CharField(choices=[('DTYCR', 'Daily Treasury Yield Curve Rates'), ('DTRYCR', 'Daily Treasury Real Yield Curve Rates')], default='DTYCR', max_length=4)),
                ('source_url', models.URLField(blank=True, max_length=250, null=True)),
                ('long_term_yield_value', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('long_term_yield_label', models.CharField(max_length=2)),
                ('short_term_yield_value', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('short_term_yield_label', models.CharField(max_length=2)),
                ('yield_comp_difference', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_inverted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='yielddata',
            name='rate_type',
            field=models.CharField(choices=[('DTYCR', 'Daily Treasury Yield Curve Rates'), ('DTRYCR', 'Daily Treasury Real Yield Curve Rates')], default='DTYCR', max_length=4),
        ),
        migrations.AddField(
            model_name='yielddata',
            name='source_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='yieldcomp',
            name='yield_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yc_app.YieldData'),
        ),
    ]
