# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yc_app', '0003_auto_20190822_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yieldcomp',
            name='yield_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_comps', to='yc_app.YieldData'),
        ),
    ]
