# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-23 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yc_app', '0004_auto_20190822_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yielddata',
            name='rate_type',
            field=models.CharField(choices=[('DTYCR', 'Daily Treasury Yield Curve Rates'), ('DTRYCR', 'Daily Treasury Real Yield Curve Rates')], default='DTYCR', max_length=10),
        ),
    ]
