# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-26 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yc_app', '0005_auto_20190823_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yielddata',
            name='data_source',
            field=models.CharField(default='U.S. Department of the Treasury', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='yieldcomp',
            unique_together=set([('rate_type', 'date', 'short_term_yield_label', 'long_term_yield_label')]),
        ),
    ]
