# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-09 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yc_app', '0007_auto_20190826_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yieldcomp',
            name='long_term_yield_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='yieldcomp',
            name='short_term_yield_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='yieldcomp',
            name='yield_comp_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
